[build]
  command = "npm run build"
  publish = ".next"

[[redirects]]
  from = "/product/*"
  to = "/product/[permalink].html"
  status = 200
  force = true


[[plugins]]
  package = "netlify-plugin-onboarding"

[template.environment]
  NEXT_PUBLIC_CHEC_PUBLIC_KEY = "Chec Public Key (under Setup > Developer)"
